version: '2'

services:

  python:
    build: docker/python
    ports:
     - "8000:8000"
    volumes:
      - "./src:/app"
    command: bash -c "pip install -r requirements_dev.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
